//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfraccionesWS.ProxyInfracciones {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PapeletaBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Final")]
    [System.SerializableAttribute()]
    public partial class PapeletaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codInfraccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecPapeletaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numPapeletaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numPlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codInfraccion {
            get {
                return this.codInfraccionField;
            }
            set {
                if ((object.ReferenceEquals(this.codInfraccionField, value) != true)) {
                    this.codInfraccionField = value;
                    this.RaisePropertyChanged("codInfraccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecPapeleta {
            get {
                return this.fecPapeletaField;
            }
            set {
                if ((this.fecPapeletaField.Equals(value) != true)) {
                    this.fecPapeletaField = value;
                    this.RaisePropertyChanged("fecPapeleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numPapeleta {
            get {
                return this.numPapeletaField;
            }
            set {
                if ((object.ReferenceEquals(this.numPapeletaField, value) != true)) {
                    this.numPapeletaField = value;
                    this.RaisePropertyChanged("numPapeleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numPlaca {
            get {
                return this.numPlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.numPlacaField, value) != true)) {
                    this.numPlacaField = value;
                    this.RaisePropertyChanged("numPlaca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyInfracciones.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPapeletasFechas", ReplyAction="http://tempuri.org/IService1/ObtenerPapeletasFechasResponse")]
        System.Collections.Generic.List<InfraccionesWS.ProxyInfracciones.PapeletaBE> ObtenerPapeletasFechas(System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPapeletasFechas", ReplyAction="http://tempuri.org/IService1/ObtenerPapeletasFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InfraccionesWS.ProxyInfracciones.PapeletaBE>> ObtenerPapeletasFechasAsync(System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPapeletasImpagasVehiculo", ReplyAction="http://tempuri.org/IService1/ObtenerPapeletasImpagasVehiculoResponse")]
        System.Collections.Generic.List<InfraccionesWS.ProxyInfracciones.PapeletaBE> ObtenerPapeletasImpagasVehiculo(string numPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPapeletasImpagasVehiculo", ReplyAction="http://tempuri.org/IService1/ObtenerPapeletasImpagasVehiculoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InfraccionesWS.ProxyInfracciones.PapeletaBE>> ObtenerPapeletasImpagasVehiculoAsync(string numPlaca);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : InfraccionesWS.ProxyInfracciones.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<InfraccionesWS.ProxyInfracciones.IService1>, InfraccionesWS.ProxyInfracciones.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<InfraccionesWS.ProxyInfracciones.PapeletaBE> ObtenerPapeletasFechas(System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ObtenerPapeletasFechas(fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InfraccionesWS.ProxyInfracciones.PapeletaBE>> ObtenerPapeletasFechasAsync(System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ObtenerPapeletasFechasAsync(fecIni, fecFin);
        }
        
        public System.Collections.Generic.List<InfraccionesWS.ProxyInfracciones.PapeletaBE> ObtenerPapeletasImpagasVehiculo(string numPlaca) {
            return base.Channel.ObtenerPapeletasImpagasVehiculo(numPlaca);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InfraccionesWS.ProxyInfracciones.PapeletaBE>> ObtenerPapeletasImpagasVehiculoAsync(string numPlaca) {
            return base.Channel.ObtenerPapeletasImpagasVehiculoAsync(numPlaca);
        }
    }
}
