//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirServiciosProyecto_WS.ProxyInscripcion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InscripcionBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Prision")]
    [System.SerializableAttribute()]
    public partial class InscripcionBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apePresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecIniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomPresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomProgramaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apePreso {
            get {
                return this.apePresoField;
            }
            set {
                if ((object.ReferenceEquals(this.apePresoField, value) != true)) {
                    this.apePresoField = value;
                    this.RaisePropertyChanged("apePreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desPrograma {
            get {
                return this.desProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.desProgramaField, value) != true)) {
                    this.desProgramaField = value;
                    this.RaisePropertyChanged("desPrograma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecFin {
            get {
                return this.fecFinField;
            }
            set {
                if ((this.fecFinField.Equals(value) != true)) {
                    this.fecFinField = value;
                    this.RaisePropertyChanged("fecFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecIni {
            get {
                return this.fecIniField;
            }
            set {
                if ((this.fecIniField.Equals(value) != true)) {
                    this.fecIniField = value;
                    this.RaisePropertyChanged("fecIni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomPreso {
            get {
                return this.nomPresoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomPresoField, value) != true)) {
                    this.nomPresoField = value;
                    this.RaisePropertyChanged("nomPreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomPrograma {
            get {
                return this.nomProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.nomProgramaField, value) != true)) {
                    this.nomProgramaField = value;
                    this.RaisePropertyChanged("nomPrograma");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyInscripcion.IServicioInscripcion")]
    public interface IServicioInscripcion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInscripcion/DoWork", ReplyAction="http://tempuri.org/IServicioInscripcion/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInscripcion/DoWork", ReplyAction="http://tempuri.org/IServicioInscripcion/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInscripcion/GetAllInscripcion", ReplyAction="http://tempuri.org/IServicioInscripcion/GetAllInscripcionResponse")]
        System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE> GetAllInscripcion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInscripcion/GetAllInscripcion", ReplyAction="http://tempuri.org/IServicioInscripcion/GetAllInscripcionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE>> GetAllInscripcionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInscripcion/GetAllInscripcionFechas", ReplyAction="http://tempuri.org/IServicioInscripcion/GetAllInscripcionFechasResponse")]
        System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE> GetAllInscripcionFechas(System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInscripcion/GetAllInscripcionFechas", ReplyAction="http://tempuri.org/IServicioInscripcion/GetAllInscripcionFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE>> GetAllInscripcionFechasAsync(System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInscripcion/GetAllInscripcionPreso", ReplyAction="http://tempuri.org/IServicioInscripcion/GetAllInscripcionPresoResponse")]
        System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE> GetAllInscripcionPreso(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInscripcion/GetAllInscripcionPreso", ReplyAction="http://tempuri.org/IServicioInscripcion/GetAllInscripcionPresoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE>> GetAllInscripcionPresoAsync(string strDNI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioInscripcionChannel : ConsumirServiciosProyecto_WS.ProxyInscripcion.IServicioInscripcion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioInscripcionClient : System.ServiceModel.ClientBase<ConsumirServiciosProyecto_WS.ProxyInscripcion.IServicioInscripcion>, ConsumirServiciosProyecto_WS.ProxyInscripcion.IServicioInscripcion {
        
        public ServicioInscripcionClient() {
        }
        
        public ServicioInscripcionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioInscripcionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInscripcionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInscripcionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE> GetAllInscripcion() {
            return base.Channel.GetAllInscripcion();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE>> GetAllInscripcionAsync() {
            return base.Channel.GetAllInscripcionAsync();
        }
        
        public System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE> GetAllInscripcionFechas(System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.GetAllInscripcionFechas(fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE>> GetAllInscripcionFechasAsync(System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.GetAllInscripcionFechasAsync(fecini, fecfin);
        }
        
        public System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE> GetAllInscripcionPreso(string strDNI) {
            return base.Channel.GetAllInscripcionPreso(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyInscripcion.InscripcionBE>> GetAllInscripcionPresoAsync(string strDNI) {
            return base.Channel.GetAllInscripcionPresoAsync(strDNI);
        }
    }
}
