//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirServiciosProyecto_WS.ProxyVisita {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisitaBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Prision")]
    [System.SerializableAttribute()]
    public partial class VisitaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apePresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apeVisitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirVisitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string disVisitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniPresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniVisitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecVisitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string motVisitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomPresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomVisitanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apePreso {
            get {
                return this.apePresoField;
            }
            set {
                if ((object.ReferenceEquals(this.apePresoField, value) != true)) {
                    this.apePresoField = value;
                    this.RaisePropertyChanged("apePreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apeVisitante {
            get {
                return this.apeVisitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.apeVisitanteField, value) != true)) {
                    this.apeVisitanteField = value;
                    this.RaisePropertyChanged("apeVisitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dirVisitante {
            get {
                return this.dirVisitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.dirVisitanteField, value) != true)) {
                    this.dirVisitanteField = value;
                    this.RaisePropertyChanged("dirVisitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string disVisitante {
            get {
                return this.disVisitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.disVisitanteField, value) != true)) {
                    this.disVisitanteField = value;
                    this.RaisePropertyChanged("disVisitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dniPreso {
            get {
                return this.dniPresoField;
            }
            set {
                if ((object.ReferenceEquals(this.dniPresoField, value) != true)) {
                    this.dniPresoField = value;
                    this.RaisePropertyChanged("dniPreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dniVisitante {
            get {
                return this.dniVisitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.dniVisitanteField, value) != true)) {
                    this.dniVisitanteField = value;
                    this.RaisePropertyChanged("dniVisitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecVisita {
            get {
                return this.fecVisitaField;
            }
            set {
                if ((this.fecVisitaField.Equals(value) != true)) {
                    this.fecVisitaField = value;
                    this.RaisePropertyChanged("fecVisita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string motVisita {
            get {
                return this.motVisitaField;
            }
            set {
                if ((object.ReferenceEquals(this.motVisitaField, value) != true)) {
                    this.motVisitaField = value;
                    this.RaisePropertyChanged("motVisita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomPreso {
            get {
                return this.nomPresoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomPresoField, value) != true)) {
                    this.nomPresoField = value;
                    this.RaisePropertyChanged("nomPreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomVisitante {
            get {
                return this.nomVisitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.nomVisitanteField, value) != true)) {
                    this.nomVisitanteField = value;
                    this.RaisePropertyChanged("nomVisitante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyVisita.IServicioVisita")]
    public interface IServicioVisita {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVisita/DoWork", ReplyAction="http://tempuri.org/IServicioVisita/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVisita/DoWork", ReplyAction="http://tempuri.org/IServicioVisita/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVisita/GetAllVisita", ReplyAction="http://tempuri.org/IServicioVisita/GetAllVisitaResponse")]
        System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE> GetAllVisita();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVisita/GetAllVisita", ReplyAction="http://tempuri.org/IServicioVisita/GetAllVisitaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE>> GetAllVisitaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVisita/GetAllVisitaFechas", ReplyAction="http://tempuri.org/IServicioVisita/GetAllVisitaFechasResponse")]
        System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE> GetAllVisitaFechas(System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVisita/GetAllVisitaFechas", ReplyAction="http://tempuri.org/IServicioVisita/GetAllVisitaFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE>> GetAllVisitaFechasAsync(System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVisita/GetAllVisitaPreso", ReplyAction="http://tempuri.org/IServicioVisita/GetAllVisitaPresoResponse")]
        System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE> GetAllVisitaPreso(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVisita/GetAllVisitaPreso", ReplyAction="http://tempuri.org/IServicioVisita/GetAllVisitaPresoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE>> GetAllVisitaPresoAsync(string strDNI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioVisitaChannel : ConsumirServiciosProyecto_WS.ProxyVisita.IServicioVisita, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioVisitaClient : System.ServiceModel.ClientBase<ConsumirServiciosProyecto_WS.ProxyVisita.IServicioVisita>, ConsumirServiciosProyecto_WS.ProxyVisita.IServicioVisita {
        
        public ServicioVisitaClient() {
        }
        
        public ServicioVisitaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioVisitaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVisitaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVisitaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE> GetAllVisita() {
            return base.Channel.GetAllVisita();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE>> GetAllVisitaAsync() {
            return base.Channel.GetAllVisitaAsync();
        }
        
        public System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE> GetAllVisitaFechas(System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.GetAllVisitaFechas(fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE>> GetAllVisitaFechasAsync(System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.GetAllVisitaFechasAsync(fecini, fecfin);
        }
        
        public System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE> GetAllVisitaPreso(string strDNI) {
            return base.Channel.GetAllVisitaPreso(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServiciosProyecto_WS.ProxyVisita.VisitaBE>> GetAllVisitaPresoAsync(string strDNI) {
            return base.Channel.GetAllVisitaPresoAsync(strDNI);
        }
    }
}
