//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_celda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_celda()
        {
            this.tb_ingreso = new HashSet<tb_ingreso>();
        }
    
        public int cod_celda { get; set; }
        public int capacidad_celda { get; set; }
        public int actual_celda { get; set; }
        public int cod_pabellon { get; set; }
    
        public virtual tb_pabellon tb_pabellon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ingreso> tb_ingreso { get; set; }
    }
}
