//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ingreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ingreso()
        {
            this.tb_detalle_ingreso = new HashSet<tb_detalle_ingreso>();
            this.tb_inscripcion = new HashSet<tb_inscripcion>();
            this.tb_visita = new HashSet<tb_visita>();
        }
    
        public int cod_ingreso { get; set; }
        public int cod_preso { get; set; }
        public int cod_celda { get; set; }
        public System.DateTime fec_ingreso { get; set; }
        public System.DateTime fec_salida { get; set; }
        public string estado { get; set; }
    
        public virtual tb_celda tb_celda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalle_ingreso> tb_detalle_ingreso { get; set; }
        public virtual tb_preso tb_preso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_inscripcion> tb_inscripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_visita> tb_visita { get; set; }
    }
}
