//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_inscripcion
    {
        public int cod_inscripcion { get; set; }
        public int cod_ingreso { get; set; }
        public int cod_programa { get; set; }
        public System.DateTime fecha_ini { get; set; }
        public System.DateTime fecha_fin { get; set; }
    
        public virtual tb_ingreso tb_ingreso { get; set; }
        public virtual tb_programa tb_programa { get; set; }
    }
}
