//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_preso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_preso()
        {
            this.tb_ingreso = new HashSet<tb_ingreso>();
        }
    
        public int cod_preso { get; set; }
        public string nom_preso { get; set; }
        public string ape_preso { get; set; }
        public string dni_preso { get; set; }
        public System.DateTime fecNac_preso { get; set; }
        public int dis_preso { get; set; }
        public string dir_preso { get; set; }
    
        public virtual tb_distrito tb_distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ingreso> tb_ingreso { get; set; }
    }
}
