//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_visitante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_visitante()
        {
            this.tb_visita = new HashSet<tb_visita>();
        }
    
        public int cod_visitante { get; set; }
        public string nom_visitante { get; set; }
        public string ape_visitante { get; set; }
        public string dni_visitante { get; set; }
        public int dis_visitante { get; set; }
        public string dir_visitante { get; set; }
    
        public virtual tb_distrito tb_distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_visita> tb_visita { get; set; }
    }
}
