//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_visita
    {
        public int cod_visita { get; set; }
        public int cod_ingreso { get; set; }
        public int cod_visitante { get; set; }
        public System.DateTime fec_visita { get; set; }
        public string motivo_visita { get; set; }
    
        public virtual tb_ingreso tb_ingreso { get; set; }
        public virtual tb_visitante tb_visitante { get; set; }
    }
}
