//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDelitosIngreso
    {
        public int cod_ingreso { get; set; }
        public System.DateTime fec_ingreso { get; set; }
        public string participacion { get; set; }
        public string des_delito { get; set; }
        public int cod_delito { get; set; }
        public int penaMax_delito { get; set; }
        public string nom_preso { get; set; }
        public string dni_preso { get; set; }
    }
}
