//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIngresosPreso
    {
        public int cod_ingreso { get; set; }
        public System.DateTime fec_ingreso { get; set; }
        public System.DateTime fec_salida { get; set; }
        public int cod_celda { get; set; }
        public string estado { get; set; }
        public int cod_preso { get; set; }
        public string dni_preso { get; set; }
        public string nom_preso { get; set; }
        public string ape_preso { get; set; }
        public string dir_preso { get; set; }
        public System.DateTime fecNac_preso { get; set; }
        public string nom_distrito { get; set; }
    }
}
