//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Prision
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVisitasIngreso
    {
        public string nom_distrito { get; set; }
        public string nom_preso { get; set; }
        public string ape_preso { get; set; }
        public string dni_preso { get; set; }
        public int cod_ingreso { get; set; }
        public System.DateTime fec_visita { get; set; }
        public string motivo_visita { get; set; }
        public string nom_visitante { get; set; }
        public string dni_visitante { get; set; }
        public string ape_visitante { get; set; }
        public int dis_visitante { get; set; }
        public string dir_visitante { get; set; }
    }
}
