//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteInfraccionesWindows.ProxyInfracciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyInfracciones.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPapeletasFechas", ReplyAction="http://tempuri.org/IService1/ObtenerPapeletasFechasResponse")]
        InfraccionesWS.ProxyInfracciones.PapeletaBE[] ObtenerPapeletasFechas(System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPapeletasFechas", ReplyAction="http://tempuri.org/IService1/ObtenerPapeletasFechasResponse")]
        System.Threading.Tasks.Task<InfraccionesWS.ProxyInfracciones.PapeletaBE[]> ObtenerPapeletasFechasAsync(System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPapeletasImpagasVehiculo", ReplyAction="http://tempuri.org/IService1/ObtenerPapeletasImpagasVehiculoResponse")]
        InfraccionesWS.ProxyInfracciones.PapeletaBE[] ObtenerPapeletasImpagasVehiculo(string numPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPapeletasImpagasVehiculo", ReplyAction="http://tempuri.org/IService1/ObtenerPapeletasImpagasVehiculoResponse")]
        System.Threading.Tasks.Task<InfraccionesWS.ProxyInfracciones.PapeletaBE[]> ObtenerPapeletasImpagasVehiculoAsync(string numPlaca);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClienteInfraccionesWindows.ProxyInfracciones.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClienteInfraccionesWindows.ProxyInfracciones.IService1>, ClienteInfraccionesWindows.ProxyInfracciones.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InfraccionesWS.ProxyInfracciones.PapeletaBE[] ObtenerPapeletasFechas(System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ObtenerPapeletasFechas(fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<InfraccionesWS.ProxyInfracciones.PapeletaBE[]> ObtenerPapeletasFechasAsync(System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ObtenerPapeletasFechasAsync(fecIni, fecFin);
        }
        
        public InfraccionesWS.ProxyInfracciones.PapeletaBE[] ObtenerPapeletasImpagasVehiculo(string numPlaca) {
            return base.Channel.ObtenerPapeletasImpagasVehiculo(numPlaca);
        }
        
        public System.Threading.Tasks.Task<InfraccionesWS.ProxyInfracciones.PapeletaBE[]> ObtenerPapeletasImpagasVehiculoAsync(string numPlaca) {
            return base.Channel.ObtenerPapeletasImpagasVehiculoAsync(numPlaca);
        }
    }
}
